<?php

namespace BalrogBundle\Repository;

/**
 * HeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeroRepository extends \Doctrine\ORM\EntityRepository
{
    public function InsertId($username,$id){
        $conn = $this->getEntityManager()->getConnection();
        $conn->update('hero', array('user_id' => $username), array('id' => $id));
    }}